name = "Улашов Суннатилла Собир Угли"
description = "Менеджер по продажам в компании VAN UNIVERSAL MOTORS"
keywords = ""
image = "Без имени-1.jpg"
theme = "light"
primary_color = "#292c35"
text_align = "center"
gtag_id = ""
base_url = "https://biloliddinabdujalilov.github.io/sunnatilla/"

[[sections]]
title = "Контакты"
description = "+99890 996 80 64"
direction = "column"
item_style = "outline"
[[sections.items]]
embed_url = "https://www.youtube.com/embed/tzYdqMRJntk?si=3yLTORA7CZQMXh33"
[[sections.items]]
title = "Telegram"
description = "+99890 996 80 64"
url = "https://t.me/998909968064"
[[sections.items]]
title = "WhatsApp"
description = "+998909968064"
url = "https://wa.me/998909968064"
[[sections.items]]
title = "E-mail"
description = "ulashovsunnatilla2002@gmail.com"
url = "mailto:ulashovsunnatilla2002@gmail.com"


[[sections]]
title = "Ссылки"
description = "Социальные сети компании VUM"
direction = "row"
item_style = "outline"
icon_size = "30px"
[[sections.items]]
icon = "https://cdn.simpleicons.org/instagram"
title = "Instagram"
url = "https://www.instagram.com/vum_faw_uzbekistan"
[[sections.items]]
icon = "https://cdn.simpleicons.org/youtube"
title = "YouTube"
url = "https://www.youtube.com/@faw_uzbekistan/"
[[sections.items]]
icon = "https://cdn.simpleicons.org/google"
title = "Сайт"
url = "https://faw.uz"
[[sections.items]]
title = "Facebook"
icon = "https://cdn.simpleicons.org/facebook"
url = "https://www.facebook.com/fawuzbekistan"
